name: CI/CD
on:
  pull_request:
    branches: [staging]
jobs:
  release:
    name: Generate git tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Generate and push git tag
        run: git tag -a v$(node -p "require('./package.json').version") -m "v$(node -p "require('./package.json').version")" && git push origin --tags --global
